ALTER TABLE products ADD COLUMN IF NOT EXISTS image2 VARCHAR(1000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS image3 VARCHAR(1000);
ALTER TABLE products ADD COLUMN IF NOT EXISTS image4 VARCHAR(1000);
